# =============================================================================
#   KITTY TERMINAL CONFIGURATION
# =============================================================================

# Desactivar sonido de campana / beep
enable_audio_bell no

# Confirmar cierre de ventana
confirm_os_window_close 0

# Tema de colores dinámico de Noctalia
include themes/noctalia.conf
