# =============================================================================
#   KITTY TERMINAL CONFIGURATION
# =============================================================================

# Desactivar sonido de campana / beep
enable_audio_bell no

# Tema de colores dinámico de Noctalia
include themes/noctalia.conf
