color0 #46464b
color1 #ffb4ab
color2 #c6c5d0
color3 #c8c5ca
color4 #d3c2ca
color5 #c6c5d0
color6 #c8c5ca
color7 #e5e2e2
color8 #919096
color9 #ffb4ab
color10 #c6c5d0
color11 #c8c5ca
color12 #d3c2ca
color13 #c6c5d0
color14 #c8c5ca
color15 #e5e2e2

cursor                #e5e2e2
cursor_text_color     #000000
background            #000000
foreground            #e5e2e2
selection_foreground  #c7c5cb
selection_background  #46464b
active_border_color   #c6c5d0
inactive_border_color #38383d
url_color             #c6c5d0

active_tab_foreground   #2f3038
active_tab_background   #c6c5d0
inactive_tab_foreground #c7c5cb
inactive_tab_background #38383d
cursor_trail_color      #c7c5cb
